### ISSUE TITLE
Etruscan: Naming places

### ISSUE THREAD

**Issue by jonathanwestin** [gu-gridh/multimodal-map#105]
Now when we have started to add places that are not part of the initial dataset, new problems appear with how we name things which merits a rethink (good thing is that we can still change everything since it is not released):

Problem 1:
If a the official name of a tomb is Tomba Rossa, then it is really weird that we automatically put tomb/tomba infront of the name (because then it will be "Tomba Tomba Rossa"). This made sense for the tombs in dataset 1 that just had numbers as names, and most times will just be numbers, but we still need a solution that does not look weird.

Possible solutions:
a) drop the tomb/tomba prefix (but then a lot of tombs will have awkwardly short names)
b) automatically insert tomb/tomba only when the first character in a name is a letter (possibly resource demanding and difficult)
c) Drop Tomb/tomba and Insert the lead researchers last name before the number in the database, i.e Tobin 1 (what happens if there are multiple researchers responsible and they have long names?).
d) Drop the tomb/tomba and Insert an abbreviation of the dataset name before the name , i.e CTSG 248 (but what happens if a place is part of more than one dataset?).

etcetera

Problem 2:
How do we make sure url's to places are unique? Right now I could for instance name anotherr object 248 (lets say we add another dataset where they have numbered all the tombs from 1-500). Then we have a conflict in the way we name our url:s. I know I argued for place names, but that was perhaps unwise unless we latch on something else to the url.

Possible solutions:
a) go back to id's (but then add a number or something to them to not make them so similar to the tomb names
b) Insert an abbreviation of the dataset name before the name , i.e CTSG 248 (but what happens if a place is part of more than one dataset?).

etcetera

please come up with more/better solutions, and preferably solutions that can be generalized for other projects so we don't have to invent the wheel again.

**Comment by jonathanwestin** [comment]
Here is one suggestion:
1) remove the tomb/tomba add-on from the frontend (Jonathan)
2) add the dataset acronym (for instance CTSG or SIR) before each tomb name: CTSG 1, CTSG 248 etc (Matteo and Tristan)
3) make the url a lowercase combination of dataset acronym and place-name separated by underscore (and replace all spaces with underscore): ctsg_1, ctsg_248, sir_casetta_1 (Tristan)

A problem that remains is what to do if more than one dataset contains a place reference for the same tomb.
Possible solutions:
a) add an "equal to" logic in the backend where one manually can connect two tombs and sort it in the frontend using that logic.
b) ?

**Comment by mtomasini** [comment]
@TristanBridge for the place-name separated by underscore (@jonathanwestin's comment, point 3), I think it would be easy enough for me to output that in the API. Any operation we do in the backend optimizes speed, no?

**Comment by jonathanwestin** [comment]
Almost done, just the "bug" when it comes to addresses like http://localhost:5173/place/SIR_Casetta_3 remains
