### ISSUE TITLE
Etruscan: Alphabetically sorting of Necropolis list and the all option

### ISSUE THREAD

**Issue by jonathanwestin** [gu-gridh/multimodal-map#106]
1) It would be nice if the necropolis were alphabetically sorted.
2) the all-option should perhaps not change focus and zoom level as we now have tombs in much wider areas.

**Comment by mtomasini** [comment]
@TristanBridge is this the `/api/etruscantombs/necropolis` that needs to be sorted?

**Comment by mtomasini** [comment]
Necropolis now appear in alphabetical order. This change modified slightly how the drop-down menu for Type of Tomb shows, do we want that in Alphabetical order too? Or something else? (I can modify it easily in the API) @jonathanwestin

**Comment by jonathanwestin** [comment]
I think all menus alphabetically sorted is fine
