### ISSUE TITLE
Data download widget

### ISSUE THREAD

**Issue by arildm** [gu-gridh/multimodal-map#11]
Something like the application download buttons here? https://biccs.dh.gu.se/2021/24/1

**Comment by jonathanwestin** [comment]
I think perhaps something simpler like we have here that is here (so basically just a link that directs towards the loaded asset that we can add to any type of button or text): https://strand.dh.gu.se/spelur/4/bild/autom/114

This will benefit all Multimodeal maps and the same type of solution is needed for SHFA.
