### ISSUE TITLE
Etruscan: San Giovenale map tile shows more detail than the rest of the area

### ISSUE THREAD

**Issue by mtomasini** [gu-gridh/multimodal-map#139]
I just noticed this by zooming out of the San Giovenale area - it seems to have more details. We should extend the area with high detail to the area where there is data.

![Screenshot from 2024-09-24 09-00-11](https://github.com/user-attachments/assets/c661260f-8f13-47f4-a5e6-986bbc745909)

**Comment by jonathanwestin** [comment]
The elevation curves are hand drawn by Fredrik Tobin-Dodd as part of the San giovenale dataset.  They are based on older maps from printed books. That is why we don't have that type of detailed data from other areas. Ultimately we would ofcourse like to have that for the whole of former Etruria, but to my knowledge Italy does not make available that type of data in a reasonable resolution so it requires a tremendous amount of manual labour (if even possible).

**Comment by mtomasini** [comment]
That's too bad. Anyhow, I'm gonna try to remember this, maybe we can find a solution at a latter stage.
