### ISSUE TITLE
Make time-span slider work with all categories

### ISSUE THREAD

**Issue by jonathanwestin** [gu-gridh/multimodal-map#14]
Currently you have to first pick a category for the slider to filter the markers, but ideally you would be able to filter everything at once when the default All Categories option is selected.

**Comment by TristanBridge** [comment]
Need back-end support. Can't filter the places by dates. for example this doesn't work: https://diana.dh.gu.se/api/rephotography/geojson/place/?page_size=500&start_date=1832&end_date=1956

but this does:
https://diana.dh.gu.se/api/rephotography/geojson/place/?page_size=500&type=image&start_date=1832&end_date=2023

**Comment by TristanBridge** [comment]
This should be working now.
