### ISSUE TITLE
Specify different types of images

### ISSUE THREAD

**Issue by jonathanwestin** [gu-gridh/multimodal-map#18]
Currently, it is presumed that all images are photographs, but some might be drawings/art or plans. Ideally, in the front end we would be able to filter to only see images of a certain type (for instances, in Rephotography only see photographs or only see drawings/art). Solutions: some sort of many when adding an image that lets the user specify image type from a list (for instance: "Photograph", "Orthophoto", "Drawing", "Plan", "Map", "Figure", "Rendering", "Print").

**Comment by AramKarimi** [comment]
I have added type to rephotography and Rwanda models. In rephotography we have separate model for type and you can update the list with new type and then select one of those on image side. But for Rwanda, type is associated with image and you can add any type you want when you're adding new image to database.
