### ISSUE TITLE
Filter widget for tags

### ISSUE THREAD

**Issue by jonathanwestin** [gu-gridh/multimodal-map#19]
Basically the same as the CategoryButtonList (and using the same CategoryButton.vue), but hooked up through APIs to the list of tags.

**Comment by TristanBridge** [comment]
Need this api: https://diana.dh.gu.se/api/rephotography/geojson/place/?page_size=500 to be able to filter by tags. Something like this: https://diana.dh.gu.se/api/rephotography/geojson/place/?page_size=500&tag=glacier if we want to filter places by their tags. we should also consider adding all the tags from the images at a place to that place as well.

**Comment by TristanBridge** [comment]
This is working except the tags can't be filtered by the date slider. Don't know if we want this functionality.
