### ISSUE TITLE
Layer switcher

### ISSUE THREAD

**Issue by arildm** [gu-gridh/multimodal-map#2]

**Comment by jonathanwestin** [comment]
Ideally I would like to be able to style a button, and add a link to that button that activates a specific layer on the map (for instance a glacier-layer). The button should have an active state (showing that particular glacier layer), and an inactive state (hiding that particular glacier layer).

**Comment by TristanBridge** [comment]
have added the lineStrings, but the polygon layer is too big currently. Will probably need to be added to Diana so I can load it based on the bbox.
Projection EPSG:4326
LineStrings
https://data.dh.gu.se/geography/glacier_front_2022.geojson
https://data.dh.gu.se/geography/glacier_front_2021.geojson
https://data.dh.gu.se/geography/glacier_front_2008.geojson
Polygons
https://data.dh.gu.se/geography/CryoClim_GAO_SJ_1936-1972.geojson 16MB
https://data.dh.gu.se/geography/CryoClim_GAO_SJ_2001-2010.geojson 21MB
