### ISSUE TITLE
Markdown for description fields

### ISSUE THREAD

**Issue by siskahumlesjo** [gu-gridh/multimodal-map#23]
Ability to add italics, bold and hyperlinks to all description fields.

**Comment by jonathanwestin** [comment]
Depending on how the implementation is most easily done in the front end, either a rich text editor or a markdown editor. I believe Tristan has experience on implementing markdown in the BICCS project.

**Comment by AramKarimi** [comment]
I implemented ReachText that gives you ability to decorate the text and change the style. We need to see how it works in front-end side and then can decide to use this or markdownfield.

**Comment by jonathanwestin** [comment]
Excellent, let us await Tristan's verdict.
