### ISSUE TITLE
Remembering closed about-view in Rephotography

### ISSUE THREAD

**Issue by jonathanwestin** [gu-gridh/multimodal-map#35]
Store the state of the about-view so it does not show every time the user goes back to main screen after having looked at media.

**Comment by TristanBridge** [comment]
the about page should only load the first time per session now.

**Comment by jonathanwestin** [comment]
Doe not reappear for me unfortunately (tries clearing cache and reloading).

**Comment by jonathanwestin** [comment]
Never mind, it was my CSS-logics that were at fault!
