### ISSUE TITLE
Category filter by type of image

### ISSUE THREAD

**Issue by jonathanwestin** [gu-gridh/multimodal-map#41]
Clicking "Drawings and art" in the category filter should filter the result down to only images that are of the image type "drawing". The category filter widget should be able too filter by any of the available image types (but we will hid impost of them in the frontend as there is not enough data to make it interesting:
print
rendering
figure
map
drawing
plan
orthophoto
photograph

**Comment by TristanBridge** [comment]
https://diana.dh.gu.se/api/rephotography/geojson/place/?page_size=500&type=observation -> works
https://diana.dh.gu.se/api/rephotography/geojson/place/?page_size=500&type=drawing -> doesn't work

type drawing doesn't exist currently, we need to add it in the backend.
