### ISSUE TITLE
Add the Bookmark-url add-on to Openseadragon

### ISSUE THREAD

**Issue by jonathanwestin** [gu-gridh/multimodal-map#42]
This one is a must for all projects that use openseadragon. This add-on (we use it on antarctica.dh.gu.se for the orthophotos), updates the url with the current zoom and pan so you can share that link with another person and they will see the same thing.
https://github.com/openseadragon/bookmark-url

**Comment by TristanBridge** [comment]
should be added now. the shared url is slightly misaligned with the original photo. Don't know if this is something in the library that is causing it.

**Comment by jonathanwestin** [comment]
When trying it is seems like it is only reading the zoom, not the pan... So if you zoom in and pan to the left on a really wide image, and copy the url, you will in the new tab get the correct zoom in, but in the centre of the image.

**Comment by jonathanwestin** [comment]
Fixed it! I changed line 63 and 71 in bookmar-url to:
self.viewport.panTo(new OpenSeadragon.Point(params.x, params.y), true);
from
self.viewport.panTo(new $.Point(params.x, params.y), true);
