### ISSUE TITLE
Rephotography: focus markers (with associated media)

### ISSUE THREAD

**Issue by jonathanwestin** [gu-gridh/multimodal-map#47]
Each image has both a place and a focus-place associated with it. Currently we are just putting the place markers on the map, but we also must put the focus markers there (perhaps with the Green marker color).

**Comment by TristanBridge** [comment]
https://diana.dh.gu.se/api/rephotography/geojson/focus/ doesn't seem to work

**Comment by AramKarimi** [comment]
I have fixed this issue and now you have access to the geography in for via:
https://diana.dh.gu.se/api/rephotography/geojson/focus/
