### ISSUE TITLE
Onboarding view

### ISSUE THREAD

**Issue by arildm** [gu-gridh/multimodal-map#8]
i.e start-view / about-view that gives more info about the project and those involved

**Comment by jonathanwestin** [comment]
This is a component that should be added to the MainLayout.vue. I would like to be able to show or dismiss this view by adding or removing a class to the div containing the class. This would allow us to use css transitions to make it fade in/out in some project and make it pop-in and out in other projects.

**Comment by jonathanwestin** [comment]
I have added an about.vue that is triggered by a visibleAbout:true state. However, this currently only works for dismissing the about view, as I cannot change the visibleAbout state to true from another vue file... See Rephotography for an example of this.

**Comment by jonathanwestin** [comment]
https://user-images.githubusercontent.com/70022179/236676952-65b9673f-d30c-41f8-bb99-5bf7310e76ca.mov
