### ISSUE TITLE
Masonry Gallery loads first "page" of image twice on first infinite scroll reload

### ISSUE THREAD

**Issue by jonathanwestin** [gu-gridh/multimodal-map#86]
This does not happen when "all" data are selected, only for filtered searches large enough to require infinite scroll loading (for instance if the user has selected to see a subset of the time periods or a large necropolis.

**Comment by jonathanwestin** [comment]
Basically a super weird bug, because it does not hhaepn for all filters all the time (but for some all the time). Sure way to experience it: 
1) go to gallery. 
2) filter by necropolis Casale Vignale
3) Note the image with Fredrik Tobin clearing away plants
4) scroll down and note that it (and all other images in the first batch) appears again.

**Comment by TristanBridge** [comment]
I think this should be resolved now.
