### ISSUE TITLE
Range slider instead of epoch buttons

### ISSUE THREAD

**Issue by jonathanwestin** [gu-gridh/multimodal-map#93]
When adding more tombs from other datasets there is quickly a need for more epoch buttons which creates a cluttered interface. I therefore propose we switch them out for a range slider. If any part of a an epoch falls within the active range then tombs with that epoch should be shown. The look could be based on the one in Rephotography, but we would also need som sort of interface to specify if we want to include tombs with unknown dates as well.

**Comment by mtomasini** [comment]
We could have a slider with few ticks, not a "continuous" one. E.g. a tick every 100 years. And also, we could split current Epoch tags into multiple centuries, and add the possibility to assign tombs to more than one tag if tag is unclear.

**Comment by jonathanwestin** [comment]
I think it will be important for the researchers to be able to have weird tags like 615-450 BC (since it is often based on historical events) or set a first date and a last date that can be quite precise. Perhaps it would be possible to convert the current tags to a first and last date (year not months and days), and let the slider show those places if the active span completely encapsulates the first and last date? Or should it show them even if it just a portion of the place tags span?

**Comment by mtomasini** [comment]
As long as the tags have a specified format (e.g. always "YEAR-YEAR BC") it's easy enough in python to split into an earliest and latest date. Then we can decide what the slider does.
