### ISSUE TITLE
Mapview filter: Combine filtering for both plans and sections in the Drawing button and data widget

### ISSUE THREAD

**Issue by jonathanwestin** [gu-gridh/multimodal-map#94]
Like how it works in PlaceView. Currently it just filters for plans.

<img width="450" alt="Skärmavbild 2023-11-03 kl  08 47 04" src="https://github.com/gu-gridh/multimodal-map/assets/70022179/de5b32f6-9838-4ef5-8a8d-194636222247">

**Comment by mtomasini** [comment]
Yeah, I tried to filter for both at the same time, but it will require some more tinkering. I know what should be done, I just didn't manage to do it properly in the few time I had last week.
