### ISSUE TITLE
Data download and api-links in the footer

### ISSUE THREAD

**Issue by jonathanwestin** [gu-gridh/multimodal-map#96]
It is important to communicate the openness of the data, so we would need to in asme clear way, link to either a GitHub page that collects all the information, or some Diana-generated page in regards to how to download the data (and then I only mean the place data, not. image and 3d models)  and description of the API's.

**Comment by jonathanwestin** [comment]
I can add it to the frontend if I get one or mor links to the above.

**Comment by mtomasini** [comment]
If you tell me what text needs to be added, I can put it on the README for etruscan tombs (https://github.com/gu-gridh/etruscantombs).

**Comment by jonathanwestin** [comment]
I have added the layout for the links in the foot and linked to https://github.com/gu-gridh/etruscantombs#etruscan-tombs. It seems to be possible to use anchors to link to specific parts of that readme, so perhaps you can make relevant subheadings and we can link directly to them. If this is also going to be the main GitHub readme file, then it would also be nice with links to the frontend code and such.

<img width="430" alt="Skärmavbild 2023-11-06 kl  21 18 40" src="https://github.com/gu-gridh/multimodal-map/assets/70022179/274e8930-97c8-4268-a3f2-845dc4c468ce">

**Comment by mtomasini** [comment]
Yes, although ideally the frontend project could have its own README? In Github you can anchor also to specific lines of a document, and it should be possible to anchor to specific parts of and .md file. I will check it out.
