### ISSUE TITLE
Dataset tag and filtering for places and media objects

### ISSUE THREAD

**Issue by jonathanwestin** [gu-gridh/multimodal-map#97]
It is important for the launch of Etruscan to communicate that it's a tool for several datasets and that visualises in the frontend where the data comes from.

Matteo: The dataset tags should be organised as a separate list in the backend. All current photographs and drawings and places can be tagged with the dataset tag CToSG2015, and I can retag things I did this summer with the dataset tag SIR.

Tristan & Jonathan: in the frontend there should be a dataset menu with "All datasets" and then the objects from the dataset tag list. This menu should both be in the map view and the place view. Furthermore, the dataset tag must be visible in the image view and 3d viewer and in the place card.

We need to link to a document where we give information about the datasets, preferably on GitHub.

**Comment by jonathanwestin** [comment]
Placement and style of dataset menus pushed!

<img width="464" alt="Skärmavbild 2023-11-05 kl  15 24 40" src="https://github.com/gu-gridh/multimodal-map/assets/70022179/5ad7b5b4-f988-4fcd-96c6-0cc78b699f21">
<img width="820" alt="Skärmavbild 2023-11-05 kl  15 29 04" src="https://github.com/gu-gridh/multimodal-map/assets/70022179/bd2aa2e1-8d20-4bca-bcac-35fb016c4f4f">

**Comment by mtomasini** [comment]
Just to understand: right now datasets are tagged using the generic tag, but you want these to be a separate category list? I can add that quite easily, adding a default tag for every object already on the database. The question is: is this tag for documentation, or for places?

Proposal:
- in places we have a multiple choice dataset: each place can be in several datasets.
- in images and documentation, we have single choice dataset. Each of these relates to only one dataset.
- do we need dataset tags for 3D models? Those are not sources of data, they are separate builds, no?

**Comment by jonathanwestin** [comment]
Regarding if positions can be part of many datasets: perhaps we should make it possible to link to another place instead and declare them the same to 1) avoid conflicts in how different researchers want to describe a tomb (what if there are two different datasets where the dame tomb is dated differently for instance) 2) keep it clean in the url.
This would of course need some work in how we presents numbers if we have many overlapping tombs/places as that would skewer the statistics. However this will probably be edge cases.
